import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage();
const errors = [];
page.on('console', msg => { if (msg.type()==='error') errors.push('CONSOLE: '+msg.text()); });
page.on('pageerror', err => errors.push('PAGEERROR: '+err.message));
page.on('requestfailed', req => errors.push('REQFAIL: '+req.url()+' '+req.failure()?.errorText));
await page.goto('http://localhost:3000/', { waitUntil: 'networkidle' });
await page.waitForTimeout(3000);
console.log('ERRORS_COUNT:', errors.length);
for (const e of errors.slice(0,15)) console.log(e.slice(0,300));
await browser.close();
