export const LIMITES = {
  PENA_MAXIMA_GENERAL_MESES: 360,
  PENA_MAXIMA_EXCEPCIONAL_MESES: 480,
  UMBRAL_VEINTE_ANOS_MESES: 240,
  FRACCION_TENTATIVA_ACABADA: 1 / 4,
  FRACCION_TENTATIVA_INACABADA: 1 / 3,
  FRACCION_COMPLICE: 1 / 3,
  FRACCION_CONCURSO_IDEAL: 1 / 3,
  FRACCION_CONTINUADO_ADICIONAL: 1 / 3,
  PENA_PERPETUA_MESES: 480,
};

export const UMBRALES_GRAVEDAD = {
  MUY_GRAVE: 360,
  GRAVE: 120,
  MENOS_GRAVE: 36,
};
