export {
  blogPosts,
  faqEntries,
  configuracionSitio,
  pageContent,
  categoriasBlog,
  categoriasFaq,
  tags,
  postsTags,
  autores,
  paginasCms,
  areasJuridicas,
  medios,
  versionesContenido,
  redirects,
  menus,
} from './core';

export type {
  BlogPost,
  BlogPostInsert,
  FaqEntry,
  FaqEntryInsert,
  ConfiguracionSitio,
  ConfiguracionSitioInsert,
  PageContent,
  PageContentInsert,
  CategoriaBlog,
  CategoriaBlogInsert,
  CategoriaFaq,
  CategoriaFaqInsert,
  Tag,
  TagInsert,
  Autor,
  AutorInsert,
  PaginaCms,
  PaginaCmsInsert,
  AreaJuridica,
  AreaJuridicaInsert,
  Medio,
  MedioInsert,
  VersionContenido,
  VersionContenidoInsert,
  Redirect,
  RedirectInsert,
  Menu,
  MenuInsert,
} from './core';
