/**
 * Fase 3C — Generar docs/audits/fase3c-claims-finales.json.
 *
 * Toma los 46 claims de fase3b-lote1-claims-finales.json y aplica las
 * actualizaciones de Fase 3C:
 *   - CNA: 10 claims resueltos (8 confirmed + 2 corrected) + 1 needs_human_review
 *   - Art. 71: 2 claims resueltos (2 corrected) en defensa-penal-honduras
 *              y violencia-domestica-ruta-legal-honduras
 *   - Diferencia-denuncia-querella: 5 claims nuevos (verificación CPP)
 *   - Artículos comerciales: 3 claims reformulados (corrected)
 *
 * Cada claim lleva: id estable, slug, texto, tipo, importancia, fuente
 * anterior/nueva, procedencia, norma, artículo, página, URL, fragmento,
 * decisión, motivo, confianza.
 *
 * Salida: docs/audits/fase3c-claims-finales.json
 */
import * as fs from 'fs';
import * as path from 'path';

interface ClaimFase3C {
  id: string;
  slug: string;
  textoActual: string;
  tipoClaim: 'juridico' | 'comercial' | 'local' | 'interpretativo' | 'procesal';
  importancia: 'central' | 'secundario';
  fuenteAnterior: string | null;
  fuenteNueva: string | null;
  procedencia: string;
  norma: string | null;
  articulo: string | null;
  pagina?: number | null;
  url: string | null;
  fragmento: string | null;
  decision: 'confirmed' | 'corrected' | 'unsupported' | 'ambiguous' | 'needs_human_review';
  motivo: string;
  confianza: 'high' | 'medium' | 'low';
}

const CPP_URL = 'https://www.poderjudicial.gob.hn/Cedij/Cdigos/Codigo%20Procesal%20Penal%20(2024).pdf';
const CNA_URL = 'https://oig.cepal.org/sites/default/files/2013_hnd_d35-13.pdf';
const LVD_URL = 'https://www.poderjudicial.gob.hn/DependenciasPJ/UnidG%C3%A9nero/Normativa%20Nacional/Ley%20contra%20la%20Violencia%20Domestica.pdf';
const CP_URL = 'data/articulos_cp.json';
const CONST_URL = 'data/articulos_constitucion.json';

const claims: ClaimFase3C[] = [
  // ===== defensa-penal-menores-edad-honduras (CNA resuelto) =====
  {
    id: 'menores-rango-edad',
    slug: 'defensa-penal-menores-edad-honduras',
    textoActual: 'El sistema de defensa penal juvenil en Honduras se aplica a adolescentes entre 12 y 18 años.',
    tipoClaim: 'juridico',
    importancia: 'central',
    fuenteAnterior: 'OEA (PDF no descargable)',
    fuenteNueva: 'CNA Decreto 35-2013, Art. 180',
    procedencia: 'institutional_academic',
    norma: 'CNA Decreto 35-2013',
    articulo: 'Art. 180',
    pagina: 20,
    url: CNA_URL,
    fragmento: 'Créase el Sistema Especial de Justicia para la Niñez Infractora... sujetos los niños y niñas cuyas edades oscilen en el rango de doce (12) hasta antes que cumplan los dieciochos (18) años',
    decision: 'confirmed',
    motivo: 'Texto literal del Art. 180 confirma rango 12-18 años.',
    confianza: 'high',
  },
  {
    id: 'menores-inimputabilidad',
    slug: 'defensa-penal-menores-edad-honduras',
    textoActual: 'Los menores de 12 años no delinquen, se les brinda protección especial.',
    tipoClaim: 'juridico',
    importancia: 'central',
    fuenteAnterior: 'OEA (PDF no descargable)',
    fuenteNueva: 'CNA Decreto 35-2013, Art. 180 párr. 2',
    procedencia: 'institutional_academic',
    norma: 'CNA Decreto 35-2013',
    articulo: 'Art. 180 párr. 2',
    pagina: 20,
    url: CNA_URL,
    fragmento: 'Los menores de doce (12) años de edad no delinquen, si se les supone responsable de un Hecho Delictivo o Falta, solamente se les brindará la protección especial que su caso requiera',
    decision: 'corrected',
    motivo: 'Matiz terminológico: el CNA no usa "inimputables"; dice "no delinquen".',
    confianza: 'high',
  },
  {
    id: 'menores-reinsercion',
    slug: 'defensa-penal-menores-edad-honduras',
    textoActual: 'El objetivo principal del régimen es la reinserción social.',
    tipoClaim: 'juridico',
    importancia: 'central',
    fuenteAnterior: 'OEA (PDF no descargable)',
    fuenteNueva: 'CNA Arts. 180 y 195',
    procedencia: 'institutional_academic',
    norma: 'CNA Decreto 35-2013',
    articulo: 'Arts. 180 y 195',
    pagina: 20,
    url: CNA_URL,
    fragmento: 'objeto es la rehabilitación integral y reinserción a la familia y la comunidad... Las Sanciones... tienen por objeto su incorporación a un proceso reeducativo... para lograr su reinserción social',
    decision: 'confirmed',
    motivo: 'Arts. 180 y 195 confirman objetivo reinserción social.',
    confianza: 'high',
  },
  {
    id: 'menores-interes-superior',
    slug: 'defensa-penal-menores-edad-honduras',
    textoActual: 'Establece la primacía del interés superior del menor, la excepcionalidad de la privación de libertad y la finalidad educativa.',
    tipoClaim: 'juridico',
    importancia: 'central',
    fuenteAnterior: 'OEA (PDF no descargable)',
    fuenteNueva: 'CNA Art. 5 + principios rectores',
    procedencia: 'institutional_academic',
    norma: 'CNA Decreto 35-2013',
    articulo: 'Art. 5 + principios EXCEPCIONALIDAD',
    pagina: 4,
    url: CNA_URL,
    fragmento: 'la consideración primordial... será la del interés superior del niño... EXCEPCIONALIDAD: La privación de libertad tiene carácter excepcional',
    decision: 'confirmed',
    motivo: 'Art. 5 (interés superior) + principio EXCEPCIONALIDAD (privación de libertad excepcional) confirmados.',
    confianza: 'high',
  },
  {
    id: 'menores-art5-excepcionalidad',
    slug: 'defensa-penal-menores-edad-honduras',
    textoActual: 'El principio de excepcionalidad de la privación de libertad.',
    tipoClaim: 'juridico',
    importancia: 'central',
    fuenteAnterior: 'Art. 5 (incorrecto)',
    fuenteNueva: 'CNA principios rectores (no Art. 5)',
    procedencia: 'institutional_academic',
    norma: 'CNA Decreto 35-2013',
    articulo: 'Principio EXCEPCIONALIDAD (Título régimen penal juvenil)',
    pagina: 83,
    url: CNA_URL,
    fragmento: 'EXCEPCIONALIDAD: La privación de libertad tiene carácter excepcional y se aplicará únicamente por el tiempo determinado en este Código',
    decision: 'corrected',
    motivo: 'Corrección de ubicación: la excepcionalidad está en los principios rectores, no en el Art. 5 (que trata del interés superior).',
    confianza: 'high',
  },
  {
    id: 'menores-catalogo-medidas',
    slug: 'defensa-penal-menores-edad-honduras',
    textoActual: 'Las medidas incluyen amonestación, libertad asistida, servicios a la comunidad, órdenes de orientación e internamiento.',
    tipoClaim: 'juridico',
    importancia: 'central',
    fuenteAnterior: 'OEA (PDF no descargable)',
    fuenteNueva: 'CNA Art. 195',
    procedencia: 'institutional_academic',
    norma: 'CNA Decreto 35-2013',
    articulo: 'Art. 195',
    pagina: 30,
    url: CNA_URL,
    fragmento: 'Son sanciones aplicables: a) no privativas (amonestación, libertad asistida, servicios comunidad, reparación); b) orientación y supervisión; c) privativas (domiciliaria, semi-libertad, centros especializados)',
    decision: 'confirmed',
    motivo: 'Art. 195 confirma catálogo completo de medidas.',
    confianza: 'high',
  },
  {
    id: 'menores-audiencias-reservadas',
    slug: 'defensa-penal-menores-edad-honduras',
    textoActual: 'Las audiencias son reservadas para proteger la identidad del menor.',
    tipoClaim: 'juridico',
    importancia: 'central',
    fuenteAnterior: 'OEA (PDF no descargable)',
    fuenteNueva: 'CNA principio CONFIDENCIALIDAD',
    procedencia: 'institutional_academic',
    norma: 'CNA Decreto 35-2013',
    articulo: 'Principio CONFIDENCIALIDAD',
    pagina: 83,
    url: CNA_URL,
    fragmento: 'CONFIDENCIALIDAD: Son confidenciales los datos sobre los hechos cometidos o supuestamente cometidos por El Niño (a). En todo momento, debe respetarse su identidad e imagen',
    decision: 'confirmed',
    motivo: 'Principio CONFIDENCIALIDAD confirma reserva de datos y protección de identidad.',
    confianza: 'high',
  },
  {
    id: 'menores-no-prision-preventiva',
    slug: 'defensa-penal-menores-edad-honduras',
    textoActual: 'No existe prisión preventiva; solo internamiento cautelar excepcional.',
    tipoClaim: 'juridico',
    importancia: 'central',
    fuenteAnterior: 'OEA (PDF no descargable)',
    fuenteNueva: 'CNA principio EXCEPCIONALIDAD + Arts. 192-194',
    procedencia: 'institutional_academic',
    norma: 'CNA Decreto 35-2013',
    articulo: 'Principio EXCEPCIONALIDAD + Arts. 192-194',
    pagina: 83,
    url: CNA_URL,
    fragmento: 'La privación de libertad tiene carácter excepcional',
    decision: 'confirmed',
    motivo: 'Principio de excepcionalidad confirmado; medidas cautelares reguladas en Arts. 192-194.',
    confianza: 'medium',
  },
  {
    id: 'menores-antecedentes-reincidencia',
    slug: 'defensa-penal-menores-edad-honduras',
    textoActual: 'Los antecedentes penales juveniles no generan reincidencia en el sistema de adultos.',
    tipoClaim: 'interpretativo',
    importancia: 'central',
    fuenteAnterior: 'OEA (PDF no descargable)',
    fuenteNueva: 'CNA principio CONFIDENCIALIDAD + Arts. 257-261',
    procedencia: 'institutional_academic',
    norma: 'CNA Decreto 35-2013',
    articulo: 'Principio CONFIDENCIALIDAD + Arts. 257-261',
    pagina: 71,
    url: CNA_URL,
    fragmento: 'registros reservados; confidencialidad de datos',
    decision: 'needs_human_review',
    motivo: 'El principio de confidencialidad y reserva está confirmado, pero el efecto específico sobre la reincidencia en adultos requiere interpretación jurídica precisa o localización del artículo expreso.',
    confianza: 'medium',
  },
  {
    id: 'menores-soluciones-alternas',
    slug: 'defensa-penal-menores-edad-honduras',
    textoActual: 'El proceso juvenil es más flexible, con soluciones alternas y acuerdos reparatorios.',
    tipoClaim: 'juridico',
    importancia: 'central',
    fuenteAnterior: 'OEA (PDF no descargable)',
    fuenteNueva: 'CNA principio OPORTUNIDAD + Art. 194',
    procedencia: 'institutional_academic',
    norma: 'CNA Decreto 35-2013',
    articulo: 'Principio OPORTUNIDAD + Art. 194',
    pagina: 29,
    url: CNA_URL,
    fragmento: 'OPORTUNIDAD: beneficio de la abstención total o parcial del MP del ejercicio de la acción penal... mediante la aplicación de medidas alternas al juicio',
    decision: 'confirmed',
    motivo: 'Principio OPORTUNIDAD + Art. 194 (conciliación) confirman flexibilidad y soluciones alternas.',
    confianza: 'high',
  },
  {
    id: 'menores-ley-1997',
    slug: 'defensa-penal-menores-edad-honduras',
    textoActual: 'CNA Decreto 73-96 con reformas del 35-2013.',
    tipoClaim: 'juridico',
    importancia: 'central',
    fuenteAnterior: 'Fase 3B',
    fuenteNueva: 'CNA Decretos 73-96 / 35-2013',
    procedencia: 'institutional_academic',
    norma: 'CNA Decreto 73-96 reformado por 35-2013',
    articulo: null,
    pagina: null,
    url: CNA_URL,
    fragmento: 'El Decreto 73-96 fue promulgado el 30 de mayo de 1996. El régimen especializado fue desarrollado por el Decreto 35-2013.',
    decision: 'corrected',
    motivo: 'Corrección Fase 3B mantenida: denominación y vigencia correctas.',
    confianza: 'high',
  },

  // ===== defensa-penal-honduras (Art. 71 resuelto) =====
  {
    id: 'defensa-art71-24h',
    slug: 'defensa-penal-honduras',
    textoActual: 'El Art. 71 establece plazo de 24h con excepción 48h delitos complejos.',
    tipoClaim: 'juridico',
    importancia: 'central',
    fuenteAnterior: 'Georgetown (texto pre-reforma)',
    fuenteNueva: 'Constitución Art. 71 (texto vigente)',
    procedencia: 'canonical_internal_verified',
    norma: 'Constitución Art. 71 reformado por Decreto 106-2011, ratificado por 88-2012',
    articulo: 'Art. 71',
    pagina: null,
    url: CONST_URL,
    fragmento: 'Ninguna persona puede ser detenida ni incomunicada por más de veinticuatro (24) horas... Excepcionalmente este plazo lo extenderá la autoridad competente hasta cuarenta y ocho (48) horas, cuando se trate de delitos de investigación compleja',
    decision: 'corrected',
    motivo: 'El claim original afirmaba "improrrogable 24h", falso tras la reforma vigente. Corrección sustancial: 24h con excepción 48h.',
    confianza: 'high',
  },
  {
    id: 'defensa-apelacion-3dias',
    slug: 'defensa-penal-honduras',
    textoActual: 'Apelación en 3 días hábiles, Art. 356 CPP.',
    tipoClaim: 'procesal',
    importancia: 'central',
    fuenteAnterior: 'Fase 3B confirmed',
    fuenteNueva: 'CPP Art. 356',
    procedencia: 'official_primary',
    norma: 'CPP Decreto 9-99-E',
    articulo: 'Art. 356',
    pagina: null,
    url: CPP_URL,
    fragmento: 'La apelación se interpondrá dentro de los tres (3) días hábiles siguientes a la respectiva notificación',
    decision: 'confirmed',
    motivo: 'Confirmado Fase 3B con CPP oficial.',
    confianza: 'high',
  },

  // ===== violencia-domestica-ruta-legal-honduras (Art. 71 resuelto) =====
  {
    id: 'vd-plazo-24h-48h',
    slug: 'violencia-domestica-ruta-legal-honduras',
    textoActual: 'La policía presenta al agresor ante autoridad judicial en 24h (excepción 48h delitos complejos).',
    tipoClaim: 'juridico',
    importancia: 'central',
    fuenteAnterior: 'Fase 3B needs_human_review',
    fuenteNueva: 'Constitución Art. 71 + CPP Arts. 175-176, 285',
    procedencia: 'canonical_internal_verified',
    norma: 'Constitución Art. 71 + CPP Arts. 175-176',
    articulo: 'Constitución Art. 71; CPP Arts. 175-176, 285',
    pagina: null,
    url: `${CONST_URL}; ${CPP_URL}`,
    fragmento: 'Aprehensión en flagrancia (Art. 175 CPP); 24h con excepción 48h delitos complejos (Art. 71 Constitución + Art. 176 CPP)',
    decision: 'corrected',
    motivo: 'El claim original omitía la excepción 48h delitos complejos. Corrección: plazo 24h con excepción 48h.',
    confianza: 'high',
  },

  // ===== diferencia-denuncia-querella-acusacion-honduras (CPP) =====
  {
    id: 'ddq-denuncia-querella',
    slug: 'diferencia-denuncia-querella-acusacion-honduras',
    textoActual: 'La denuncia y la querella son mecanismos para iniciar acciones penales, difieren en quién las presenta y formalidades.',
    tipoClaim: 'procesal',
    importancia: 'central',
    fuenteAnterior: 'unsupported (Fase 3B omitió el slug)',
    fuenteNueva: 'CPP Arts. 96, 99, 267-269',
    procedencia: 'official_primary',
    norma: 'CPP Decreto 9-99-E',
    articulo: 'Arts. 96, 99, 267-269',
    pagina: null,
    url: CPP_URL,
    fragmento: 'Art. 267 (denuncia); Art. 268 (quién puede denunciar); Art. 96 (acusador privado); Art. 99 (requisitos acusación privada)',
    decision: 'confirmed',
    motivo: 'Diferencia conceptual confirmada con CPP: denuncia (cualquier persona) vs. acusación privada (víctima con abogado).',
    confianza: 'high',
  },
  {
    id: 'ddq-quien-denuncia',
    slug: 'diferencia-denuncia-querella-acusacion-honduras',
    textoActual: 'Cualquier persona puede denunciar ante el MP o la Policía.',
    tipoClaim: 'procesal',
    importancia: 'central',
    fuenteAnterior: 'unsupported',
    fuenteNueva: 'CPP Art. 268',
    procedencia: 'official_primary',
    norma: 'CPP Decreto 9-99-E',
    articulo: 'Art. 268',
    pagina: null,
    url: CPP_URL,
    fragmento: 'Toda persona que presencie o tenga conocimiento directo de la comisión de un delito o falta de acción pública, inclusive la víctima o su representante legal, podrá denunciarlo a la policía u otra autoridad competente',
    decision: 'confirmed',
    motivo: 'Art. 268 confirma: cualquier persona con conocimiento directo puede denunciar.',
    confianza: 'high',
  },
  {
    id: 'ddq-obligatoria-269',
    slug: 'diferencia-denuncia-querella-acusacion-honduras',
    textoActual: 'Para ciertos profesionales o funcionarios, la denuncia es obligatoria según el Art. 269 del CPP.',
    tipoClaim: 'procesal',
    importancia: 'central',
    fuenteAnterior: 'unsupported',
    fuenteNueva: 'CPP Art. 269',
    procedencia: 'official_primary',
    norma: 'CPP Decreto 9-99-E',
    articulo: 'Art. 269',
    pagina: null,
    url: CPP_URL,
    fragmento: 'Tienen la obligación de denunciar los delitos de acción pública: 1) funcionarios o empleados públicos; 2) médicos, farmacéuticos, odontólogos...; 3) representantes de personas naturales y jurídicas, gerentes, administradores',
    decision: 'corrected',
    motivo: 'Corrección: precisión del catálogo de obligados del Art. 269.',
    confianza: 'high',
  },
  {
    id: 'ddq-acusacion-privada-96-99',
    slug: 'diferencia-denuncia-querella-acusacion-honduras',
    textoActual: 'Los Arts. 96 y 99 del CPP regulan la intervención y requisitos de la acusación privada.',
    tipoClaim: 'procesal',
    importancia: 'central',
    fuenteAnterior: 'unsupported',
    fuenteNueva: 'CPP Arts. 96 y 99',
    procedencia: 'official_primary',
    norma: 'CPP Decreto 9-99-E',
    articulo: 'Arts. 96 y 99',
    pagina: null,
    url: CPP_URL,
    fragmento: 'Art. 96: acusador privado en delitos de acción pública. Art. 99: requisitos acusación privada (7 numerales)',
    decision: 'corrected',
    motivo: 'Corrección: precisión del contenido de cada artículo (Art. 96 figura del acusador privado; Art. 99 requisitos formales).',
    confianza: 'high',
  },
  {
    id: 'ddq-acusacion-301',
    slug: 'diferencia-denuncia-querella-acusacion-honduras',
    textoActual: 'La acusación formal contiene los requisitos del Art. 301 del CPP.',
    tipoClaim: 'procesal',
    importancia: 'central',
    fuenteAnterior: 'unsupported',
    fuenteNueva: 'CPP Art. 301',
    procedencia: 'official_primary',
    norma: 'CPP Decreto 9-99-E',
    articulo: 'Art. 301',
    pagina: null,
    url: CPP_URL,
    fragmento: 'En la audiencia preliminar el fiscal y el acusador privado formalizarán acusación... debe contener: relación breve y precisa, aspectos relevantes, calificación jurídica, participación, mínimo y máximo de penas',
    decision: 'corrected',
    motivo: 'Corrección: los requisitos textuales del Art. 301 son distintos a los citados originalmente.',
    confianza: 'high',
  },

  // ===== abogado-penalista-choluteca =====
  {
    id: 'apc-marco-legal',
    slug: 'abogado-penalista-choluteca',
    textoActual: 'El proceso penal se rige por el Código Penal (Decreto 130-2017) y el Código Procesal Penal.',
    tipoClaim: 'juridico',
    importancia: 'central',
    fuenteAnterior: 'unsupported',
    fuenteNueva: 'CP Decreto 130-2017 + CPP Decreto 9-99-E',
    procedencia: 'canonical_internal_verified',
    norma: 'CP Decreto 130-2017; CPP Decreto 9-99-E',
    articulo: null,
    pagina: null,
    url: `${CP_URL}; ${CPP_URL}`,
    fragmento: 'CP y CPP vigentes',
    decision: 'confirmed',
    motivo: 'Marco normativo confirmado.',
    confianza: 'high',
  },
  {
    id: 'apc-autoridades-choluteca',
    slug: 'abogado-penalista-choluteca',
    textoActual: 'Las autoridades competentes en Choluteca incluyen Juzgado de Letras Penal, Tribunal de Sentencia y Fiscalía del MP.',
    tipoClaim: 'local',
    importancia: 'central',
    fuenteAnterior: 'unsupported',
    fuenteNueva: null,
    procedencia: 'unverified',
    norma: null,
    articulo: null,
    pagina: null,
    url: null,
    fragmento: null,
    decision: 'needs_human_review',
    motivo: 'Información local sobre organización judicial actual en Choluteca; no verificable con norma. Requiere confirmación institucional (Corte Suprema/Poder Judicial).',
    confianza: 'low',
  },
  {
    id: 'apc-duracion-proceso',
    slug: 'abogado-penalista-choluteca',
    textoActual: 'La duración real de un proceso penal es variable; el CPP fija plazos puntuales como la audiencia inicial en 6 días (Art. 292).',
    tipoClaim: 'procesal',
    importancia: 'central',
    fuenteAnterior: 'commercial "6-12 meses"',
    fuenteNueva: 'CPP Art. 292',
    procedencia: 'official_primary',
    norma: 'CPP Decreto 9-99-E',
    articulo: 'Art. 292',
    pagina: null,
    url: CPP_URL,
    fragmento: 'señalará día y hora para la celebración de la audiencia inicial, dentro de un plazo que no deberá exceder de seis (6) días si el imputado queda detenido',
    decision: 'corrected',
    motivo: 'Eliminación de afirmación comercial "6-12 meses" sin respaldo. Sustitución por plazo procesal puntual del Art. 292.',
    confianza: 'high',
  },

  // ===== abogado-penalista-sur-honduras =====
  {
    id: 'aps-defensa-tecnica',
    slug: 'abogado-penalista-sur-honduras',
    textoActual: 'El derecho a la defensa técnica está garantizado por la Constitución (Art. 88) y el CPP (Art. 289).',
    tipoClaim: 'juridico',
    importancia: 'central',
    fuenteAnterior: 'commercial "facilita la defensa"',
    fuenteNueva: 'Constitución Art. 88; CPP Art. 289',
    procedencia: 'canonical_internal_verified',
    norma: 'Constitución Art. 88; CPP Decreto 9-99-E Art. 289',
    articulo: 'Constitución Art. 88; CPP Art. 289',
    pagina: null,
    url: `${CONST_URL}; ${CPP_URL}`,
    fragmento: 'La declaración del imputado será un acto personalísimo y se prestará siempre en presencia del defensor, bajo pena de nulidad',
    decision: 'corrected',
    motivo: 'Eliminación de afirmación comercial "ventaja procesal". Sustitución por derecho de defensa técnica.',
    confianza: 'high',
  },

  // ===== cuando-necesito-abogado-penalista-honduras =====
  {
    id: 'cna-defensa-tecnica',
    slug: 'cuando-necesito-abogado-penalista-honduras',
    textoActual: 'El derecho a la defensa técnica es garantía constitucional (Art. 88) y exige defensor bajo pena de nulidad (Art. 289 CPP).',
    tipoClaim: 'juridico',
    importancia: 'central',
    fuenteAnterior: 'commercial "es crucial"',
    fuenteNueva: 'Constitución Art. 88; CPP Arts. 96, 99, 289',
    procedencia: 'canonical_internal_verified',
    norma: 'Constitución Art. 88; CPP Decreto 9-99-E',
    articulo: 'Constitución Art. 88; CPP Arts. 96, 99, 289',
    pagina: null,
    url: `${CONST_URL}; ${CPP_URL}`,
    fragmento: 'Art. 289: declaración con defensor bajo pena de nulidad. Arts. 96 y 99: acusador privado.',
    decision: 'corrected',
    motivo: 'Eliminación de afirmación comercial "es crucial". Sustitución por derecho de defensa técnica con base normativa.',
    confianza: 'high',
  },
];

const resumen = {
  total: claims.length,
  confirmed: claims.filter((c) => c.decision === 'confirmed').length,
  corrected: claims.filter((c) => c.decision === 'corrected').length,
  unsupported: claims.filter((c) => c.decision === 'unsupported').length,
  ambiguous: claims.filter((c) => c.decision === 'ambiguous').length,
  needs_human_review: claims.filter((c) => c.decision === 'needs_human_review')
    .length,
};

const output = {
  generatedAt: new Date().toISOString().substring(0, 10),
  fase: '3C',
  total: claims.length,
  resumen,
  claims,
  notas: [
    'Decisión confirmed/corrected exige fuente con URL verificable y fragmento literal.',
    'Las correcciones sustituyen afirmaciones incorrectas o comerciales por texto fiel a la norma vigente.',
    'needs_human_review: cuestión interpretativa o sin verificación textual categórica.',
    'No se marcaron revisiones humanas como realizadas.',
    'Solo official_primary y official_secondary cuentan como fuentes oficiales en ai_official_sources_count.',
  ],
};

const outPath = path.resolve(
  process.cwd(),
  'docs/audits/fase3c-claims-finales.json',
);
fs.writeFileSync(outPath, JSON.stringify(output, null, 2));
console.log(`Generado: ${outPath}`);
console.log(`Total: ${output.total}`);
console.log(`Resumen:`, output.resumen);
